name: Main Pipeline

on:
  push

permissions:
  contents: read
  packages: read
  statuses: write
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Upgrade pip & install Semgrep
        run: |
          python -m pip install --upgrade pip 
          pip install semgrep

      - name: Run Semgrep
        run: semgrep --config auto --error || true

      - name: Semgrep JSON report
        run: semgrep --config auto --error --json -o semgrep.json || true
      - name: Semgrep SARIF report
        run: semgrep --config auto --error --sarif -o semgrep.sarif || true
      - name: Semgrep JUnit report
        run: semgrep --config auto --error --junit-xml -o semgrep-junit.xml || true

      - name: Upload Semgrep to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        
      - name: Upload Semgrep artifacts
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-reports
          path: |
            semgrep.json
            semgrep.sarif
            semgrep-junit.xml
          
  trivy:
    runs-on: ubuntu-latest
    needs: 
      - semgrep
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout (full history for better scanning)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app image (for image scanning)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: app-under-test:latest
          push: false
          load: true

      - name: Decide Trivy exit-code (block on main only)
        id: trivy_mode
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "code=1" >> "$GITHUB_OUTPUT"
          else
            echo "code=0" >> "$GITHUB_OUTPUT"
          fi
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: .cache/trivy
          key: trivy-db-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            trivy-db-${{ runner.os }}-
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_CACHE_DIR: .cache/trivy
          TRIVY_SKIP_DIRS: .git,.cache,trivy,node_modules,dist,build
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-fs.sarif
          scanners: vuln,secret,license
          severity: CRITICAL,HIGH,MEDIUM
          ignore-unfixed: true
          cache-dir: .cache/trivy
          exit-code: ${{ steps.trivy_mode.outputs.code }}

      - name: Upload SARIF (Trivy FS)
        if: always() && github.repository_owner == github.actor
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs
          wait-for-processing: false   

      - name: Upload artifact (Trivy FS)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs
          path: trivy-fs.sarif

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_CACHE_DIR: .cache/trivy
        with:
          scan-type: image
          image-ref: app-under-test:latest
          format: sarif
          output: trivy-image.sarif
          scanners: vuln,secret,license
          severity: CRITICAL,HIGH,MEDIUM
          ignore-unfixed: true
          cache-dir: .cache/trivy
          exit-code: ${{ steps.trivy_mode.outputs.code }}

      - name: Upload SARIF (Trivy Image)
        if: always() && github.repository_owner == github.actor
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
          category: trivy-image
          wait-for-processing: false   

      - name: Upload artifact (Trivy Image)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image
          path: trivy-image.sarif

  snyk-iac:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - semgrep
      - trivy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Snyk Infrastructure as Code scan
        uses: snyk/actions/iac@master
        with:
          args: test --debug
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SEVERITY_THRESHOLD: "critical"
          FILE: "example-*"
          update_pr_with_scan_results: true
        continue-on-error: true
 
  gitleaks:
    runs-on: ubuntu-latest
    if: always()
    needs: 
      - semgrep
      - trivy
      - snyk-iac
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE_KEY }}

      - name: Upload Gitleaks SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

  zap:
    name: ZAP
    runs-on: ubuntu-latest
    if: always() # -- will proceed kahit nag fail si gitleaks
    needs: 
        - gitleaks
        - semgrep
        - trivy
        - snyk-iac

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: app-under-test:latest
          push: false
          load: true

      - name: Run app container
        run: docker run -d --name aut -p 8080:80 app-under-test:latest

      - name: Wait for app to be ready
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:8080/ > /dev/null; then
              echo "App is up."
              exit 0
            fi
            echo "Waiting for app... ($i/60)"
            sleep 2
          done
          echo "App did not start in time."
          docker logs aut || true
          exit 1
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-r zap_report.html -w zap_report.md -J zap_report.json'

      - name: Upload ZAP reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap_report.html
            zap_report.md
            zap_report.json
      - name: Cleanup
        if: always()

        run: docker rm -f aut || true



